version: '3.9'

services:
  backend:
    build: ./backend
    container_name: projeto-ecommerce-backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always

  frontend:
    build: ./frontend
    container_name: projeto-ecommerce-frontend
    ports:
      - "3000:80"
    restart: always
